# Generated by Django 3.2.21 on 2023-09-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('oia', 'OIÁ with 1 bed for 2 persons'), ('ogum', 'OGUM with 6 beds for 6 persons')], max_length=20),
        ),
    ]
