# Generated by Django 3.2.21 on 2023-09-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_auto_20230918_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('Oiá', 'Oiá'), ('Ogum', 'Ogum')], max_length=20),
        ),
    ]
