# Generated by Django 3.2.21 on 2023-09-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_auto_20230919_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('Oia', 'OIÁ with 1 bed for 2 persons'), ('Ogum', 'OGUM with 2 beds for 2 persons')], max_length=20),
        ),
    ]
