# Generated by Django 3.2.21 on 2023-09-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('oia', 'OIÁ with 1 bed for 2 persons'), ('ogum', 'OGUM with 2 beds for 2 persons')], max_length=20),
        ),
    ]
